### ISSUE TITLE
Dropbox down

### ISSUE THREAD

**Issue by retrim** [rawleyfowler/linux-wse-installer#1]
https://uc3bd31d1e17c211be84021132ce.dl.dropboxusercontent.com/cd/0/get/COeSuNPgqmCrrG0nbZTJGbtrr_LFkek1A-EtlTU7wcjcwHwP4l_0Ru_H56WmPC8n61V7-kmQwWwoZEX7e6kWO638_Atg8S3B1Dxe1nmQh0dbxgTlIw3OPZTeuo9K_J2332pIhMCpThpPStoMUJBGHYKturnwDz1jXfS4F_E7X_6HZNokbz15S1Q3OSIJJjna7T4/file?_download_id=112312138116793862100185768518991759948644830848378993135077522405&_notify_domain=www.dropbox.com&dl=1

Has been deleted?

**Comment by rawleyfowler** [comment]
@retrim Thanks for opening an issue. The drop-box for WSE stuff gets changed from time to time, so the URL will have to be updated.

**Comment by rawleyfowler** [comment]
Please run `git pull` and try installing again. I've updated the URL.

**Comment by rawleyfowler** [comment]
Closing this, as it seems to work for others now. Feel free to re-open this if it comes back.
